name: Build & Push WOSPI-vanilla (ARM64)

on:
  push:
    #paths:
    #  - 'Dockerfile.wospi'
    #  - 'build.env'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm64   # native ARM64 Runner

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load build environment
        run: |
          sed -i 's/\r$//' build.env
          source build.env

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          echo "OS_IMAGE=$OS_IMAGE" >> $GITHUB_ENV
          echo "OS_TAG=$OS_TAG" >> $GITHUB_ENV
          echo "CONT_VER=$CONT_VER" >> $GITHUB_ENV
          echo "WOSPI_VERSION=$WOSPI_VERSION" >> $GITHUB_ENV
          echo "WOSPI_RELEASE_DATE=$WOSPI_RELEASE_DATE" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      - name: Define image tags
        run: |
          echo "TAG_BUILD=${CONT_VER}-${BUILD}" >> $GITHUB_ENV
          echo "TAG_VERSION=${CONT_VER}" >> $GITHUB_ENV
          echo "TAG_LATEST=latest" >> $GITHUB_ENV

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push WOSPI-vanilla (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.wospi
          platforms: ${{ env.PLATFORM }}  # z.B. linux/arm64
          push: true
          build-args: |
            OS_IMAGE=${{ env.OS_IMAGE }}
            OS_TAG=${{ env.OS_TAG }}
            CONT_VER=${{ env.CONT_VER }}
            WOSPI_VERSION=${{ env.WOSPI_VERSION }}
            WOSPI_RELEASE_DATE=${{ env.WOSPI_RELEASE_DATE }}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.TAG_BUILD }}
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest

