name: Build WOSPI Images

on:
  push:
    paths:
      - Dockerfile.*
      - build.env
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:
  build-slim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load env
        run: |
          sed -i 's/\r$//' build.env
          source build.env
          echo "OS_TAG=$OS_TAG" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push slim
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.slim
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/wospi-slim:${{ env.OS_TAG }}

  build-base:
    needs: build-slim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load env
        run: |
          sed -i 's/\r$//' build.env
          source build.env
          echo "OS_TAG=$OS_TAG" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          platforms: ${{ env.PLATFORM }}
          push: true
          build-args: |
            OS_IMAGE=${{ secrets.DOCKERHUB_USER }}/wospi-slim
            OS_TAG=${{ env.OS_TAG }}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/wospi-base:${{ env.OS_TAG }}

  build-vanilla:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load env
        run: |
          sed -i 's/\r$//' build.env
          source build.env
          echo "CONT_VER=$CONT_VER" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push vanilla
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.wospi
          platforms: ${{ env.PLATFORM }}
          push: true
          build-args: |
            OS_IMAGE=${{ secrets.DOCKERHUB_USER }}/wospi-base
            OS_TAG=latest
            CONT_VER=${{ env.CONT_VER }}
            WOSPI_VERSION=${{ env.WOSPI_VERSION }}
            WOSPI_RELEASE_DATE=${{ env.WOSPI_RELEASE_DATE }}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/wospi-vanilla:${{ env.CONT_VER }}-${{ env.BUILD }}
            ${{ secrets.DOCKERHUB_USER }}/wospi-vanilla:${{ env.CONT_VER }}
            ${{ secrets.DOCKERHUB_USER }}/wospi-vanilla:latest

